name: frontend CI/CD

on:
  push:
    branches:
      - feature**
      - fix**
  pull_request:
    branches:
      - dev
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run lint
        run: bun run lint
      - name: Run test
        run: bun test
  create_pull_request:
    if: github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.LARAVEL_GITHUB_ACTION_TEST }}
            commit-message: PR:Merge changes from feature/fix branch
            branch: dev
            title: 'PR: Merge changes from feature/fix branch'
            body: |
              This pull request is automatically created from the successful test of feature/fix branch.
